export const CITIES_LIST = [
	'Кампала',
	'Пхукет',
	'Санто-Доминго',
	'Дубай',
	'Шанхай',
	'Лос-Анжелес',
	'Мадрид',
	'Париж',
	'Лондон',
	'Москва',
	'Осло',
	'Мурманск',
];
export const CITIES_INFO = {
	cities: [
		{ city: 'Кампала', country: 'Кампала', latitude: 0 },
		{ city: 'Пхукет', country: 'Тайланд', latitude: 8 },
		{ city: 'Санто-Доминго', country: 'Доминикана ', latitude: 18 },
		{ city: 'Дубай', country: 'Арабские Эмираты', latitude: 25 },
		{ city: 'Шанхай', country: 'Китай', latitude: 31 },
		{ city: 'Лос-Анжелес', country: 'США', latitude: 34 },
		{ city: 'Мадрид', country: 'Испания ', latitude: 40 },
		{ city: 'Париж', country: 'Франция', latitude: 49 },
		{ city: 'Лондон', country: 'Великобритания', latitude: 52 },
		{ city: 'Москва', country: 'Россия', latitude: 56 },
		{ city: 'Осло', country: 'Норвегия', latitude: 60 },
		{ city: 'Мурманск', country: 'Россия', latitude: 69 },
	],
};
export const MONTHS_LIST = [
	'января',
	'февраля',
	'марта',
	'апреля',
	'мая',
	'июня',
	'июля',
	'августа',
	'сентября',
	'октября',
	'ноября',
	'декабря',
];
